name: Deploy Multicontainer
on:
  push:
    branches:
      - main
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - run: docker build -t rwijupal3058/client -f ./client/Dockerfile.dev ./client
      - run: docker run -e CI=true rwijupal3058/client npm test

      - run: docker build -t rwijupal3058/worker ./worker
      - run: docker build -t rwijupal3058/server ./server
      - run: docker build -t rwijupal3058/nginx ./nginx
      - run: docker build -t rwijupal3058/client ./client

      - run: docker push rwijupal3058/worker
      - run: docker push rwijupal3058/server
      - run: docker push rwijupal3058/nginx
      - run: docker push rwijupal3058/client

      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'
 
      - name: Deploy to AWS
        uses: einaregilsson/beanstalk-deploy@v18
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }} 
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          application_name: MultiContainer
          environment_name: Multicontainer-env
          existing_bucket_name: elasticbeanstalk-ap-south-1-422709438327
          region: ap-south-1
          version_label: ${{ github.sha }}
          deployment_package: deploy.zip 
